In [1]:
import pandas as pd
from detoxify import Detoxify
import numpy as np

In [2]:
tsv = pd.read_csv('final.tsv', sep='\t')
tsv

,Story Primary ID,Story ID,User Primary ID,User ID,Gender,Age,Title,Narrative,Media,Account Created Date,...,geo_name,long,lat,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
0,156581,STY1666112066,86625,USR1662300553,NaN,12,Qatar Airways cuts flights to accommodate FIFA...,"<p dir=""ltr"">Qatar Airways&#160;has withdrawn ...",https://image.pixstory.com/Pixstory-image-1666...,2022/9/4 19:39,...,NaN,NaN,NaN,0.000436,0.000001,0.000031,0.000085,0.000124,0.000016,0.000012
1,156580,STY1666111954,119236,USR1665943314,NaN,18,Positive thinking does not necessarily mean av...,"<p dir=""ltr"">Positive thinking does not necess...",https://image.pixstory.com/Pixstory-image-1666...,2022/10/16 23:31,...,NaN,NaN,NaN,0.000491,0.000001,0.000028,0.000073,0.000146,0.000017,0.000019
2,156579,STY1666111923,86566,USR1662294899,NaN,12,FIFA negotiating 'initiatives' for Qatar migra...,"<p dir=""ltr"">FIFA's president sought Monday to...",https://image.pixstory.com/Pixstory-image-1666...,2022/9/4 18:04,...,"['South Africa', 'Gulf County']","['24.0', '-85.26101']","['-29.0', '29.90862']",0.003164,0.000017,0.000059,0.004033,0.000701,0.000048,0.000369
3,156578,STY1666111798,86655,USR1662303432,NaN,12,Qatar ready for the World Cup in just over a m...,"<p dir=""ltr"">Ticket sales for the FIFA World C...",https://image.pixstory.com/Pixstory-image-1666...,2022/9/4 20:27,...,['United Arab Emirates'],['54.5'],['23.75'],0.000421,0.000002,0.000042,0.000097,0.000098,0.000016,0.000018
4,156577,STY1666111463,9221,USR1632727815,male,23,"Froyo always makes everyone happy, make this h...","<p dir=""ltr""></p>\r\n<p dir=""ltr"">Almost all o...",https://image.pixstory.com/Pixstory-image-1666...,2021/9/27 13:00,...,NaN,NaN,NaN,0.000514,0.000001,0.000037,0.000085,0.000149,0.000021,0.000017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94995,69290,STY1642159740,21189,USR1642158120,NaN,21,Bts,Bts j hope,https://image.pixstory.com/Pixstory-image-1642...,2022/1/14 16:32,...,NaN,NaN,NaN,0.000503,0.000001,0.000028,0.000097,0.000108,0.000026,0.000013
94996,69289,STY1642159721,21194,USR1642158805,female,18,I LOVE SHARK TANK INDIA,It's breathe of fresh air in a polluted enviro...,https://image.pixstory.com/Pixstory-image-1642...,2022/1/14 16:43,...,NaN,NaN,NaN,0.000530,0.000001,0.000026,0.000077,0.000150,0.000019,0.000014
94997,69288,STY1642159611,21203,USR1642159306,NaN,21,Patanjali-Good for health.,I use this Ayurveda product for boosting my im...,https://image.pixstory.com/Pixstory-image-1642...,2022/1/14 16:51,...,NaN,NaN,NaN,0.000377,0.000001,0.000027,0.000070,0.000097,0.000021,0.000015
94998,69287,STY1642159601,21202,USR1642159269,NaN,22,Football League,Me and my friend playing football inside our c...,https://image.pixstory.com/Pixstory-image-1642...,2022/1/14 16:51,...,NaN,NaN,NaN,0.000535,0.000001,0.000042,0.000086,0.000125,0.000022,0.000021
94999,69286,STY1642159578,21096,USR1642151996,NaN,19,Come back stronger like the waves,"And now that you don’t have to be perfect, you...",https://image.pixstory.com/Pixstory-image-1642...,2022/1/14 14:49,...,NaN,NaN,NaN,0.001799,0.000002,0.000101,0.000128,0.000301,0.000075,0.000045

In [3]:
tsv.columns

Index(['Story Primary ID', 'Story ID', 'User Primary ID', 'User ID', 'Gender',
       'Age', 'Title', 'Narrative', 'Media', 'Account Created Date',
       'Interest', 'ifHate', 'ifSarcasm', 'Film', 'Sport', 'Postive Words 1',
       'Postive Words 2', 'Postive Words 3', 'Europe Holiday',
       'Americas Holiday', 'Asia Holiday', 'Africa Holiday', 'Oceania Holiday',
       'Public Holiday Or Not', 'Covid Cases', 'Covid Deaths', 'Covid Tests',
       'Covid Vaccinations', 'Image Caption', 'Detected Objects',
       'tika_language', 'google_language', 'rtg_translate', 'geo_name', 'long',
       'lat', 'Toxicity', 'Severe_Toxicity', 'Obscenity', 'Identity_Attack',
       'Insult', 'Threat', 'Sexual_Explicit'],
      dtype='object')

In [4]:
tsv.Toxicity = tsv.Toxicity.astype(float).fillna(0.0)
tsv.Severe_Toxicity = tsv.Severe_Toxicity.astype(float).fillna(0.0)
tsv.Obscenity = tsv.Obscenity.astype(float).fillna(0.0)
tsv.Identity_Attack = tsv.Identity_Attack.astype(float).fillna(0.0)
tsv.Insult = tsv.Insult.astype(float).fillna(0.0)
tsv.Threat = tsv.Threat.astype(float).fillna(0.0)
tsv.Sexual_Explicit = tsv.Sexual_Explicit.astype(float).fillna(0.0)

In [5]:
# extract valuable columns
df = tsv[['ifHate', 'ifSarcasm', 'rtg_translate', 'Toxicity', 'Severe_Toxicity', 'Obscenity', 'Identity_Attack',
       'Insult', 'Threat', 'Sexual_Explicit']]

In [6]:
# create 4 sub-dataframes according to the ifHate and ifSarcasm lable
hate = df[df['ifHate'] == True]
sarcasm = df[df['ifSarcasm'] == True]
nothate = df[df['ifHate'] == False]
notsarcasm = df[df['ifSarcasm'] == False]

In [7]:
# stats of rows being labled as hate speech
hate.describe()

,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
count,1246.000000,1246.000000,1246.000000,1246.000000,1246.000000,1246.000000,1246.000000
mean,0.006469,0.000025,0.002127,0.002213,0.001559,0.000086,0.001056
std,0.036932,0.000272,0.030911,0.014624,0.019228,0.000279,0.015258
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000573,0.000002,0.000055,0.000113,0.000130,0.000020,0.000022
50%,0.000843,0.000004,0.000093,0.000186,0.000188,0.000028,0.000045
75%,0.001739,0.000009,0.000167,0.000511,0.000364,0.000046,0.000120
max,0.959638,0.009330,0.923579,0.343057,0.648131,0.004787,0.468540

In [8]:
# setting the threshold to 0.5, any entry with a value >= 0.5 is considered toxic/obscene/insulting/...
# count how many rows are considered problematic by both methods
hate[(hate['Toxicity']>=0.5) | (hate['Severe_Toxicity']>=0.5) | (hate['Obscenity']>=0.5) 
     | (hate['Identity_Attack']>=0.5) | (hate['Insult']>=0.5) | (hate['Threat']>=0.5) 
     | (hate['Sexual_Explicit']>=0.5)].describe()

,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
count,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000
mean,0.959638,0.00933,0.923579,0.016089,0.648131,0.000523,0.003306
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.959638,0.00933,0.923579,0.016089,0.648131,0.000523,0.003306
25%,0.959638,0.00933,0.923579,0.016089,0.648131,0.000523,0.003306
50%,0.959638,0.00933,0.923579,0.016089,0.648131,0.000523,0.003306
75%,0.959638,0.00933,0.923579,0.016089,0.648131,0.000523,0.003306
max,0.959638,0.00933,0.923579,0.016089,0.648131,0.000523,0.003306

In [9]:
# get number of problematic posts of each category
print('Number of toxic post: '+str(hate[(hate['Toxicity']>=0.5)].shape[0]))
print('Number of severely toxic post: '+str(hate[(hate['Severe_Toxicity']>=0.5)].shape[0]))
print('Number of obscene post: '+str(hate[(hate['Obscenity']>=0.5)].shape[0]))
print('Number of indentity attacking post: '+str(hate[hate['Identity_Attack']>=0.5].shape[0]))
print('Number of insulting post: '+str(hate[(hate['Insult']>=0.5)].shape[0]))
print('Number of threatening post: '+str(hate[(hate['Threat']>=0.5)].shape[0]))
print('Number of sexual explicit post: '+str(hate[(hate['Sexual_Explicit']>=0.5)].shape[0]))

Number of toxic post: 1
Number of severely toxic post: 0
Number of obscene post: 1
Number of indentity attacking post: 0
Number of insulting post: 1
Number of threatening post: 0
Number of sexual explicit post: 0

In [10]:
# stats of rows being labled as not hate speech
nothate.describe()

,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
count,93754.000000,93754.000000,93754.000000,93754.000000,93754.000000,93754.000000,93754.000000
mean,0.011599,0.000040,0.002604,0.001527,0.003870,0.000437,0.002468
std,0.062658,0.001478,0.033360,0.013696,0.035999,0.010007,0.031774
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000489,0.000001,0.000031,0.000083,0.000123,0.000019,0.000014
50%,0.000772,0.000002,0.000056,0.000120,0.000181,0.000027,0.000024
75%,0.002123,0.000006,0.000137,0.000345,0.000442,0.000055,0.000082
max,0.996834,0.203792,0.991341,0.818293,0.989978,0.893525,0.979708

In [11]:
# setting the threshold to 0.5, any entry with a value >= 0.5 is considered toxic/obscene/insulting/...
# count how many rows are considered problematic by both methods
nothate[(nothate['Toxicity']>=0.5) | (nothate['Severe_Toxicity']>=0.5) | (nothate['Obscenity']>=0.5) 
     | (nothate['Identity_Attack']>=0.5) | (nothate['Insult']>=0.5) | (nothate['Threat']>=0.5) 
     | (nothate['Sexual_Explicit']>=0.5)].describe()

,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
count,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000,517.000000
mean,0.674935,0.004720,0.264285,0.031538,0.285213,0.028175,0.193153
std,0.227223,0.019292,0.319771,0.104491,0.320616,0.113786,0.297567
min,0.104771,0.000006,0.000198,0.000203,0.002077,0.000027,0.000043
25%,0.526376,0.000230,0.007663,0.001944,0.023750,0.000247,0.001104
50%,0.689446,0.000778,0.075555,0.005056,0.123025,0.000618,0.006875
75%,0.876301,0.002164,0.536766,0.012491,0.517514,0.001326,0.414062
max,0.996834,0.203792,0.991341,0.818293,0.989978,0.893525,0.979708

In [12]:
# get number of problematic posts of each category
print('Number of toxic post: '+str(nothate[(nothate['Toxicity']>=0.5)].shape[0]))
print('Number of severely toxic post: '+str(nothate[(nothate['Severe_Toxicity']>=0.5)].shape[0]))
print('Number of obscene post: '+str(nothate[(nothate['Obscenity']>=0.5)].shape[0]))
print('Number of indentity attacking post: '+str(nothate[nothate['Identity_Attack']>=0.5].shape[0]))
print('Number of insulting post: '+str(nothate[(nothate['Insult']>=0.5)].shape[0]))
print('Number of threatening post: '+str(nothate[(nothate['Threat']>=0.5)].shape[0]))
print('Number of sexual explicit post: '+str(nothate[(nothate['Sexual_Explicit']>=0.5)].shape[0]))

Number of toxic post: 427
Number of severely toxic post: 0
Number of obscene post: 143
Number of indentity attacking post: 11
Number of insulting post: 137
Number of threatening post: 8
Number of sexual explicit post: 127

In [13]:
# stats of rows being labled as sarcasm
sarcasm.describe()

,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
count,3498.000000,3498.000000,3498.000000,3498.000000,3498.000000,3498.000000,3498.000000
mean,0.021485,0.000114,0.003775,0.002971,0.003317,0.000328,0.021702
std,0.080014,0.003500,0.040350,0.027245,0.029174,0.003567,0.089952
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000529,0.000001,0.000026,0.000081,0.000123,0.000022,0.000012
50%,0.000815,0.000002,0.000043,0.000104,0.000178,0.000030,0.000019
75%,0.003499,0.000007,0.000198,0.000334,0.000587,0.000085,0.000116
max,0.990867,0.203792,0.991341,0.524751,0.924350,0.096535,0.959312

In [14]:
# setting the threshold to 0.5, any entry with a value >= 0.5 is considered toxic/obscene/insulting/...
# count how many rows are considered problematic by both methods
sarcasm[(sarcasm['Toxicity']>=0.5) | (sarcasm['Severe_Toxicity']>=0.5) | (sarcasm['Obscenity']>=0.5) 
     | (sarcasm['Identity_Attack']>=0.5) | (sarcasm['Insult']>=0.5) | (sarcasm['Threat']>=0.5) 
     | (sarcasm['Sexual_Explicit']>=0.5)].describe()

,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
count,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000
mean,0.501504,0.006913,0.163199,0.045363,0.093611,0.001086,0.448252
std,0.274283,0.030057,0.303007,0.113547,0.207113,0.001025,0.283464
min,0.141950,0.000110,0.001393,0.001734,0.002077,0.000142,0.000588
25%,0.294260,0.000458,0.010941,0.006080,0.004761,0.000613,0.137056
50%,0.406188,0.000725,0.026720,0.010102,0.008144,0.000792,0.540824
75%,0.703541,0.001749,0.119006,0.017642,0.077195,0.001187,0.622375
max,0.990867,0.203792,0.991341,0.524751,0.924350,0.006177,0.959312

In [15]:
# get number of problematic posts of each category
print('Number of toxic post: '+str(sarcasm[(sarcasm['Toxicity']>=0.5)].shape[0]))
print('Number of severely toxic post: '+str(sarcasm[(sarcasm['Severe_Toxicity']>=0.5)].shape[0]))
print('Number of obscene post: '+str(sarcasm[(sarcasm['Obscenity']>=0.5)].shape[0]))
print('Number of indentity attacking post: '+str(sarcasm[sarcasm['Identity_Attack']>=0.5].shape[0]))
print('Number of insulting post: '+str(sarcasm[(sarcasm['Insult']>=0.5)].shape[0]))
print('Number of threatening post: '+str(sarcasm[(sarcasm['Threat']>=0.5)].shape[0]))
print('Number of sexual explicit post: '+str(sarcasm[(sarcasm['Sexual_Explicit']>=0.5)].shape[0]))

Number of toxic post: 18
Number of severely toxic post: 0
Number of obscene post: 6
Number of indentity attacking post: 2
Number of insulting post: 3
Number of threatening post: 0
Number of sexual explicit post: 32

In [16]:
# stats of rows being labled as not sarcasm
notsarcasm.describe()

,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
count,91502.000000,91502.000000,91502.000000,91502.000000,91502.000000,91502.000000,91502.000000
mean,0.011151,0.000037,0.002553,0.001482,0.003860,0.000436,0.001713
std,0.061587,0.001331,0.033030,0.012910,0.036061,0.010105,0.026714
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000488,0.000001,0.000032,0.000083,0.000123,0.000019,0.000014
50%,0.000773,0.000002,0.000057,0.000122,0.000182,0.000027,0.000024
75%,0.002082,0.000006,0.000137,0.000347,0.000437,0.000054,0.000082
max,0.996834,0.203616,0.989618,0.818293,0.989978,0.893525,0.979708

In [17]:
# setting the threshold to 0.5, any entry with a value >= 0.5 is considered toxic/obscene/insulting/...
# count how many rows are considered problematic by both methods
notsarcasm[(notsarcasm['Toxicity']>=0.5) | (notsarcasm['Severe_Toxicity']>=0.5) | (notsarcasm['Obscenity']>=0.5) 
     | (notsarcasm['Identity_Attack']>=0.5) | (notsarcasm['Insult']>=0.5) | (notsarcasm['Threat']>=0.5) 
     | (notsarcasm['Sexual_Explicit']>=0.5)].describe()

,Toxicity,Severe_Toxicity,Obscenity,Identity_Attack,Insult,Threat,Sexual_Explicit
count,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000,472.000000
mean,0.692441,0.004516,0.275533,0.030158,0.304654,0.030757,0.167890
std,0.215180,0.017915,0.321013,0.103487,0.323779,0.118775,0.287072
min,0.104771,0.000006,0.000198,0.000203,0.002294,0.000027,0.000043
25%,0.537275,0.000183,0.006686,0.001863,0.036282,0.000228,0.000857
50%,0.703929,0.000792,0.089180,0.004455,0.141490,0.000547,0.005486
75%,0.883370,0.002221,0.544501,0.012002,0.526686,0.001353,0.188866
max,0.996834,0.203616,0.989618,0.818293,0.989978,0.893525,0.979708

In [18]:
# get number of problematic posts of each category
print('Number of toxic post: '+str(notsarcasm[(notsarcasm['Toxicity']>=0.5)].shape[0]))
print('Number of severely toxic post: '+str(notsarcasm[(notsarcasm['Severe_Toxicity']>=0.5)].shape[0]))
print('Number of obscene post: '+str(notsarcasm[(notsarcasm['Obscenity']>=0.5)].shape[0]))
print('Number of indentity attacking post: '+str(notsarcasm[notsarcasm['Identity_Attack']>=0.5].shape[0]))
print('Number of insulting post: '+str(notsarcasm[(notsarcasm['Insult']>=0.5)].shape[0]))
print('Number of threatening post: '+str(notsarcasm[(notsarcasm['Threat']>=0.5)].shape[0]))
print('Number of sexual explicit post: '+str(notsarcasm[(notsarcasm['Sexual_Explicit']>=0.5)].shape[0]))

Number of toxic post: 410
Number of severely toxic post: 0
Number of obscene post: 138
Number of indentity attacking post: 9
Number of insulting post: 135
Number of threatening post: 8
Number of sexual explicit post: 95